<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sk_isotope_gallery"
 *
 * Auto generated by Extension Builder 2013-11-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Isotope Gallery',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Soeren Kroell',
	'author_email' => 'kroell@idseven.de',
	'author_company' => 'iD.SEVEN',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.00',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>